parsers:
  javascript:
    enable_partials: 'yes'
# docs on codecov flags: https://docs.codecov.io/docs/flags
coverage:
  status:
    project:
      default: off
      create-fusion-app:
        flags: create-fusion-app
      create-fusion-plugin:
        flags: create-fusion-plugin
      eslint-config-fusion:
        flags: eslint-config-fusion
      fusion-cli:
        flags: fusion-cli
      fusion-core:
        flags: fusion-core
      fusion-plugin-apollo:
        flags: fusion-plugin-apollo
      fusion-plugin-browser-performance-emitter:
        flags: fusion-plugin-browser-performance-emitter
      fusion-plugin-connected-react-router:
        flags: fusion-plugin-connected-react-router
      fusion-plugin-csrf-protection:
        flags: fusion-plugin-csrf-protection
      fusion-plugin-error-handling:
        flags: fusion-plugin-error-handling
      fusion-plugin-font-loader-react:
        flags: fusion-plugin-font-loader-react
      fusion-plugin-http-handler:
        flags: fusion-plugin-http-handler
      fusion-plugin-i18n:
        flags: fusion-plugin-i18n
      fusion-plugin-i18n-react:
        flags: fusion-plugin-i18n-react
      fusion-plugin-introspect:
        flags: fusion-plugin-introspect
      fusion-plugin-jwt:
        flags: fusion-plugin-jwt
      fusion-plugin-node-performance-emitter:
        flags: fusion-plugin-node-performance-emitter
      fusion-plugin-react-helmet-async:
        flags: fusion-plugin-react-helmet-async
      fusion-plugin-react-redux:
        flags: fusion-plugin-react-redux
      fusion-plugin-react-router:
        flags: fusion-plugin-react-router
      fusion-plugin-redux-action-emitter-enhancer:
        flags: fusion-plugin-redux-action-emitter-enhancer
      fusion-plugin-rpc:
        flags: fusion-plugin-rpc
      fusion-plugin-rpc-redux-react:
        flags: fusion-plugin-rpc-redux-react
      fusion-plugin-service-worker:
        flags: fusion-plugin-service-worker
      fusion-plugin-styletron-react:
        flags: fusion-plugin-styletron-react
      fusion-plugin-universal-events:
        flags: fusion-plugin-universal-events
      fusion-plugin-universal-events-react:
        flags: fusion-plugin-universal-events-react
      fusion-plugin-universal-logger:
        flags: fusion-plugin-universal-logger
      fusion-plugin-web-app-manifest:
        flags: fusion-plugin-web-app-manifest
      fusion-react:
        flags: fusion-react
      fusion-rpc-redux:
        flags: fusion-rpc-redux
      fusion-scaffolder:
        flags: fusion-scaffolder
      fusion-test-utils:
        flags: fusion-test-utils
      fusion-tokens:
        flags: fusion-tokens
flags:
  create-fusion-app:
    paths:
      - create-fusion-app/
  create-fusion-plugin:
    paths:
      - create-fusion-plugin/
  eslint-config-fusion:
    paths:
      - eslint-config-fusion/
  fusion-cli:
    paths:
      - fusion-cli/
  fusion-core:
    paths:
      - fusion-core/
  fusion-plugin-apollo:
    paths:
      - fusion-plugin-apollo/
  fusion-plugin-browser-performance-emitter:
    paths:
      - fusion-plugin-browser-performance-emitter/
  fusion-plugin-connected-react-router:
    paths:
      - fusion-plugin-connected-react-router/
  fusion-plugin-csrf-protection:
    paths:
      - fusion-plugin-csrf-protection/
  fusion-plugin-error-handling:
    paths:
      - fusion-plugin-error-handling/
  fusion-plugin-font-loader-react:
    paths:
      - fusion-plugin-font-loader-react/
  fusion-plugin-http-handler:
    paths:
      - fusion-plugin-http-handler/
  fusion-plugin-i18n:
    paths:
      - fusion-plugin-i18n/
  fusion-plugin-i18n-react:
    paths:
      - fusion-plugin-i18n-react/
  fusion-plugin-introspect:
    paths:
      - fusion-plugin-introspect/
  fusion-plugin-jwt:
    paths:
      - fusion-plugin-jwt/
  fusion-plugin-node-performance-emitter:
    paths:
      - fusion-plugin-node-performance-emitter/
  fusion-plugin-react-helmet-async:
    paths:
      - fusion-plugin-react-helmet-async/
  fusion-plugin-react-redux:
    paths:
      - fusion-plugin-react-redux/
  fusion-plugin-react-router:
    paths:
      - fusion-plugin-react-router/
  fusion-plugin-redux-action-emitter-enhancer:
    paths:
      - fusion-plugin-redux-action-emitter-enhancer/
  fusion-plugin-rpc:
    paths:
      - fusion-plugin-rpc/
  fusion-plugin-rpc-redux-react:
    paths:
      - fusion-plugin-rpc-redux-react/
  fusion-plugin-service-worker:
    paths:
      - fusion-plugin-service-worker/
  fusion-plugin-styletron-react:
    paths:
      - fusion-plugin-styletron-react/
  fusion-plugin-universal-events:
    paths:
      - fusion-plugin-universal-events/
  fusion-plugin-universal-events-react:
    paths:
      - fusion-plugin-universal-events-react/
  fusion-plugin-universal-logger:
    paths:
      - fusion-plugin-universal-logger/
  fusion-plugin-web-app-manifest:
    paths:
      - fusion-plugin-web-app-manifest/
  fusion-react:
    paths:
      - fusion-react/
  fusion-rpc-redux:
    paths:
      - fusion-rpc-redux/
  fusion-scaffolder:
    paths:
      - fusion-scaffolder/
  fusion-test-utils:
    paths:
      - fusion-test-utils/
  fusion-tokens:
    paths:
      - fusion-tokens/
